"""unique owner_user_id on businesses

Revision ID: 52accea33d4c
Revises: cce7c11dfb5b
Create Date: 2026-08-05 19:43:49.205755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52accea33d4c'
down_revision: Union[str, Sequence[str], None] = 'cce7c11dfb5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businesses_owner_user_id'), table_name='businesses')
    op.create_index(op.f('ix_businesses_owner_user_id'), 'businesses', ['owner_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businesses_owner_user_id'), table_name='businesses')
    op.create_index(op.f('ix_businesses_owner_user_id'), 'businesses', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###
